name: test_app
description: An example app for web benchmarks testing.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  web_benchmarks:
    path: ../../

flutter:
  uses-material-design: true
