name: image_picker_for_web_integration_tests
publish_to: none

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker_for_web:
    path: ../
  image_picker_platform_interface: ^2.8.0

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  js: ^0.6.3
