name: google_identity_services_web_example
description: An example for the google_identity_services_web package, OneTap.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_identity_services_web:
    path: ../
  http: ">=0.13.0 <2.0.0"
  js: ^0.6.4

dev_dependencies:
  build_runner: ^2.1.10 # To extract README excerpts only.
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
