name: test_plugin_example
description: Pigeon test harness for primary plugin languages.
publish_to: 'none'

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_test_plugin_code:
    path: ../../shared_test_plugin_code
  test_plugin:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
