name: google_maps_flutter_web_integration_tests
publish_to: none

# Tests require flutter beta or greater to run.
environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter_platform_interface: ^2.2.1
  google_maps_flutter_web:
    path: ../

dev_dependencies:
  build_runner: ^2.1.1
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  google_maps: ^6.1.0
  google_maps_flutter: ^2.2.0 # Needed for projection_test.dart
  http: ">=0.13.0 <2.0.0"
  integration_test:
    sdk: flutter
  mockito: 5.4.1
